name: 'Create or Update Branch and Add File'
description: 'Creates or updates a branch in the repository and adds a file, overwriting if it exists'

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Create or Update Branch and Add File
      shell: bash
      run: |
        # Configure Git
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Check if branch exists
        if git ls-remote --heads origin version; then
          branch_exists=true
        else
          branch_exists=false
        fi

        # Create or switch to branch
        if [ "$branch_exists" = true ]; then
          git fetch origin
          git checkout version
          git pull origin version
        else
          git checkout --orphan version
          git rm -rf .
          echo "0.1.0" > verison
          git add version
          git commit -m "Create blank branch and add file"
          git push origin version
        fi

        # Add or overwrite file in branch
        if [ "$branch_exists" = true ]; then
          echo "0.1.0" > version
          git add version
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Add or update file in branch version"
            git push origin version
          fi
        fi
