---
name: "Create Branch Action"
description: "Adds a branch and file to branch if it does not exist"
author: "Isha Sathe"

inputs:
  branch-name:
    description: "branch name"

outputs:
  branch-name:
    description: "branch name"

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create new branch 
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b version
        git push origin version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
