---
name: "Create Branch Action"
description: "Adds a branch and file to branch if it does not exist"
author: "Isha Sathe"

inputs:
  branch-name:
    description: "branch name"
  token:
    description: "token"
    required: true
  initial-version:
    description: "init version"
    default: "0.1.0"

outputs:
  branch-name:
    description: "branch name"

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Configure git
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-action[bot]"
        git config --global http.https://github.com/.extraheader "Authorization: Bearer ${{ inputs.token }}"

    - name: Check if branch exists
      id: check-branch
      shell: bash
      run: |
        if git ls-remote --heads origin version; then
          echo "branch_exists=true" >> $GITHUB_ENV
        else
          echo "branches_exists=false" >> $GITHUB_ENV
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Create new branch or switch to branch
      shell: bash
      run: |
        if ["${{ env.branch_exists }}" = "true" ]; then
          git checkout version
        else
          git checkout -b version
          git push origin version
        fi

    - name: Add or overwrite version file
      shell: bash
      run: |
        echo "${{ inputs.initial-version }}" > version
        git add version
        git commit -m "add or update file in version"
        git push origin version

    - name: Add version file
      shell: bash
      run: |
        echo "$ {{ inputs.initial-version }}" > version
        git add version
        git commit -m "verion file added"
        git push origin version
