name: 'Create or Update Branch and Add File'
description: 'Creates or updates a branch in the repository and adds a file, overwriting if it exists'
inputs:
  version-file-branch:
    description: 'The name of the branch'
    default: "version"
  version-file:
    description: 'The path of the file to add'
  initial-version:
    description: 'The content of the file to add'
    default: "0.1.0"
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Create or Update Branch and Add File
      shell: bash
      run: |
        # Configure Git
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Check if branch exists
        if git ls-remote --heads origin ${{ inputs.version-file-branch }}; then
          branch_exists=true
        else
          branch_exists=false
        fi

        # Create or switch to branch
        if [ "$branch_exists" = true ]; then
          git checkout ${{ inputs.version-file-branch }}
          git pull origin ${{ inputs.version-file-branch }}
        else
          git checkout --orphan ${{ inputs.version-file-branch }}
          git rm -rf .
          echo "${{ inputs.initial-version }}" > ${{ inputs.version-file }}
          git add ${{ inputs.version-file }}
          git commit -m "Create blank branch and add file"
          git push origin ${{ inputs.version-file-branch }}
        fi

        # Add or overwrite file in branch
        if [ "$branch_exists" = true ]; then
          echo "${{ inputs.initial-version }}" > ${{ inputs.version-file }}
          git add ${{ inputs.version-file }}
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Add or update file in branch ${{ inputs.version-file-branch }}"
            git push origin ${{ inputs.version-file-branch }}
          fi
        fi
