---
name: Scenario Tests
on:
  workflow_dispatch:

jobs:
  Scenario_1:
    name: Default Inputs
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: create_branch_default_inputs
        name: Create Branch Default Inputs
        uses: ./
        with:
          token: $ {{ secrets.GITHUB_TOKEN }}
